### PR TITLE
added dictionary used to create pandas table of words (with example)

### PR DESCRIPTION
**Pull request by mattlianje**

### CODE REVIEW

**Comment by tjlam** [comment]
LGTM - I'm assuming this is some pre-work to be able to analyze the text?

**Comment by mattlianje** [comment]
@tjlam well - it would just require videoObject.getAudio() to have been called

**Review by tjlam — DISMISSED** [review]
Resolve the conflicts then we gucci 🕺

**Review by ewega — APPROVED** [review]
Vibin

**Pull request merged**
