### PR TITLE
Model Real World Example

### PR DESCRIPTION
**Pull request by ewega**
Kinda WIP if you guys have any feedback on what we should add, not gonna push until we get the pipeline ready and get highlight timestamps for videos from [Kevin's List](https://docs.google.com/document/d/1z8wuHj3VP4kRlV5mgmC049i1KGTIRQaAwnFzO5zLHTY/edit?fbclid=IwAR2Lz4Ds5wHeAgEXBRaiRiTm-Caqc78-Yfpvgs5QRssfszq2PvHU2VassBM)

We'll use one of these vids on this notebook to show to Ada and Stan. Lmk if I should add anything.

### CODE REVIEW

**Review by mattlianje — CHANGES_REQUESTED** [review]
I'm guessing it works for you but I had to change some stuff on db conn (first screenshot) and then it gets funky (2nd screenshot)
1st sc
image
2nd sc
image

**Review by mattlianje — DISMISSED** [review]
skrrt)

**Comment by ewega** [comment]
Concerning @mattlianje comment on this PR, that was an oopsie by me. Fixed along with stuff I added. lmk if the graphs aren't too intuitive or any other feedback

**Review by mattlianje — APPROVED** [review]
In the words of the great Joe Budden - "lets wrap it up"

**Pull request merged**
